import React from "react";
import { StatusBadge } from "./StatusBadge";

interface HistoryRow {
  runId: string;
  generatedBy: string;
  date: string;
  successful: number;
  failed: number;
  skipped: number;
  status: string;
}

export const GenerationHistoryTab: React.FC<{ rows: HistoryRow[] }> = ({ rows }) => {
  return (
    <div className="overflow-auto rounded-xl border border-[#D7E1ED] bg-white dark:border-slate-700 dark:bg-slate-800">
      <table className="w-full text-sm" aria-label="Generation history table">
        <thead className="bg-[#EBF0F7] text-left dark:bg-slate-700">
          <tr>
            <th className="p-3">Run ID</th>
            <th className="p-3">Generated by</th>
            <th className="p-3">Date</th>
            <th className="p-3">Success</th>
            <th className="p-3">Failed</th>
            <th className="p-3">Skipped</th>
            <th className="p-3">Status</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.runId} className="border-t border-[#E4EAF2] dark:border-slate-700">
              <td className="p-3">{row.runId}</td>
              <td className="p-3">{row.generatedBy}</td>
              <td className="p-3">{new Date(row.date).toLocaleString()}</td>
              <td className="p-3">{row.successful}</td>
              <td className="p-3">{row.failed}</td>
              <td className="p-3">{row.skipped}</td>
              <td className="p-3"><StatusBadge status={row.status === "failed" ? "failed" : "generated"} /></td>
            </tr>
          ))}
          {rows.length === 0 && <tr><td className="p-8 text-center text-slate-500" colSpan={7}>No class summary has been generated yet.</td></tr>}
        </tbody>
      </table>
    </div>
  );
};
