import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { AppProvider } from "@/app/context/AppContext";
import { AuthProvider } from "@/app/context/AuthContext";
import { QueryProvider } from "@/providers/query-provider";
import { WebSocketProvider } from "@/app/context/WebSocketContext";
import { ChatProvider } from "@/app/context/ChatContext";
import OnboardingShell from "./onboarding-provider";
import { ToastViewport } from "@/components/CustomToast";
import { ThemeProvider } from "@/providers/theme-provider";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Talim Teachers",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/svg+xml" href="/icons/talim.svg" />
        {/* A web manifest is required for iOS home-screen web push. */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('talim_teacher_theme')||'system';var d=window.matchMedia('(prefers-color-scheme: dark)').matches;if(t==='dark'||(t==='system'&&d)){document.documentElement.classList.add('dark')}}catch(e){}})()`,
          }}
        />
      </head>
      <body className={manrope.className}>
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              <AppProvider>
                <OnboardingShell>
                  <WebSocketProvider>
                    <ChatProvider>
                      {children}
                      <ToastViewport />
                    </ChatProvider>
                  </WebSocketProvider>
                </OnboardingShell>
              </AppProvider>
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
