import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { AppProvider } from "@/app/context/AppContext";
import { WebSocketProvider } from "@/app/contexts/WebSocketContext";
import { Toaster } from "react-hot-toast";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Talim Teachers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <AppProvider>
          <WebSocketProvider>
            {children}
            <Toaster position="top-right" />
          </WebSocketProvider>
        </AppProvider>
      </body>
    </html>
  );
}
