import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { AppProvider } from "@/app/context/AppContext";
import { WebSocketProvider } from "@/app/contexts/WebSocketContext";
import { ChatProvider } from "@/app/context/ChatContext";
import OnboardingShell from "./onboarding-provider";
import { ToastViewport } from "@/components/CustomToast";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Talim Teachers",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/icons/talim.svg" />
      </head>
      <body className={manrope.className}>
        <AppProvider>
          <OnboardingShell>
            <WebSocketProvider>
              <ChatProvider>
                {children}
                <ToastViewport />
              </ChatProvider>
            </WebSocketProvider>
          </OnboardingShell>
        </AppProvider>
      </body>
    </html>
  );
}
